# frozen_string_literal: true

module Zora
  module Rings
    NAMES = %w(
      FriendshipRing
      PowerRingL1
      PowerRingL2
      PowerRingL3
      ArmorRingL1
      ArmorRingL2
      ArmorRingL3
      RedRing
      BlueRing
      GreenRing
      CursedRing
      ExpertsRing
      BlastRing
      RangRingL1
      GBATimeRing
      MaplesRing
      SteadfastRing
      PegasusRing
      TossRing
      HeartRingL1
      HeartRingL2
      SwimmersRing
      ChargeRing
      LightRingL1
      LightRingL2
      BombersRing
      GreenLuckRing
      BlueLuckRing
      GoldLuckRing
      RedLuckRing
      GreenHolyRing
      BlueHolyRing
      RedHolyRing
      SnowshoeRing
      RocsRing
      QuicksandRing
      RedJoyRing
      BlueJoyRing
      GoldJoyRing
      GreenJoyRing
      DiscoveryRing
      RangRingL2
      OctoRing
      MoblinRing
      LikeLikeRing
      SubrosianRing
      FirstGenRing
      SpinRing
      BombproofRing
      EnergyRing
      DoubleEdgeRing
      GBANatureRing
      SlayersRing
      RupeeRing
      VictoryRing
      SignRing
      HundredthRing
      WhispRing
      GashaRing
      PeaceRing
      ZoraRing
      FistRing
      WhimsicalRing
      ProtectionRing
    ).freeze
  end
end
